from typing import Protocol, runtime_checkable
from ..models.database import TableInfo


@runtime_checkable
class AccessAdapter(Protocol):
    """Abstract interface for MS Access operations."""

    def connect(self, db_path: str) -> bool: ...

    def disconnect(self) -> None: ...

    def is_connected(self) -> bool: ...

    def get_tables(self) -> list[TableInfo]: ...

    def execute_query(self, sql: str, params: list | None = None) -> list[dict]: ...

    def launch_access(self, visible: bool = False) -> None: ...

    def close_access(self) -> None: ...

    def set_vba_code(self, module_name: str, code: str) -> bool: ...
