from typing import Protocol, runtime_checkable
from ..models.database import (
    TableInfo,
    FormInfo,
    ReportInfo,
    MacroInfo,
    ModuleInfo,
    ControlInfo,
    RelationshipInfo,
    QueryInfo,
    LinkedTableInfo,
)
from ..models.migration import TableSchema, UnknownMetadata


@runtime_checkable
class AccessAdapter(Protocol):
    """Abstract interface for MS Access operations."""

    def connect(self, db_path: str) -> bool: ...

    def disconnect(self) -> None: ...

    def is_connected(self) -> bool: ...

    def get_tables(self) -> list[TableInfo]: ...

    def execute_query(self, sql: str, params: list | None = None) -> dict: ...

    def insert_data(self, table_name: str, data: dict | list[dict]) -> dict: ...

    def update_data(self, table_name: str, set_dict: dict, where_dict: dict | str | None = None) -> dict: ...

    def delete_data(self, table_name: str, where_dict: dict | str | None = None) -> dict: ...

    def export_table_csv(self, table_or_query: str, file_path: str, delimiter: str = ",", header: bool = True) -> dict: ...

    def export_query_json(self, query_name: str, file_path: str, pretty: bool = False) -> dict: ...

    def get_queries(self) -> list[QueryInfo]: ...

    def create_query(self, name: str, sql: str) -> dict: ...

    def set_query_sql(self, name: str, sql: str) -> dict: ...

    def delete_query(self, name: str) -> dict: ...

    def create_table(self, table_name: str, columns: list[dict]) -> dict: ...

    def delete_table(self, table_name: str) -> dict: ...

    def launch_access(self, visible: bool = False) -> None: ...

    def close_access(self) -> None: ...

    def set_vba_code(self, module_name: str, code: str) -> bool: ...

    def get_forms(self) -> list[FormInfo]: ...

    def get_reports(self) -> list[ReportInfo]: ...

    def get_macros(self) -> list[MacroInfo]: ...

    def get_modules(self) -> list[ModuleInfo]: ...

    def get_vba_code(self, module_name: str) -> str: ...

    def get_system_tables(self) -> list[TableInfo]: ...

    def form_exists(self, form_name: str) -> bool: ...

    def get_form_controls(self, form_name: str) -> list[ControlInfo]: ...

    def export_form_to_text(self, form_name: str) -> str: ...

    def import_form_from_text(self, form_name: str, form_data: str) -> bool: ...

    def delete_form(self, form_name: str) -> bool: ...

    def export_report_to_text(self, report_name: str) -> str: ...

    def import_report_from_text(self, report_name: str, report_data: str) -> bool: ...

    def delete_report(self, report_name: str) -> bool: ...

    def add_vba_procedure(self, module_name: str, procedure_name: str, code: str) -> bool: ...

    def compile_vba(self) -> dict: ...

    def save_database(self) -> dict: ...

    def open_form(self, form_name: str) -> bool: ...

    def close_form(self, form_name: str) -> bool: ...

    def get_control_properties(self, form_name: str, control_name: str) -> dict: ...

    def set_control_property(self, form_name: str, control_name: str, property_name: str, value: str) -> bool: ...

    def get_object_metadata(self, object_name: str) -> dict: ...

    def get_relationships(self) -> list[RelationshipInfo]: ...

    def generate_sql(self, output_path: str) -> dict: ...

    def execute_sql_script(self, script_path: str) -> dict: ...

    def export_module_to_text(self, module_name: str) -> str: ...

    def export_macro_to_text(self, macro_name: str) -> str: ...

    def delete_module(self, module_name: str) -> bool: ...

    def export_all_versioning(self, output_dir: str) -> dict: ...

    def get_linked_tables(self) -> dict: ...

    def create_linked_table(self, name: str, source_table: str, connect_string: str) -> dict: ...

    def refresh_linked_table(self, name: str) -> dict: ...

    def unlink_table(self, name: str) -> dict: ...

    def compact_repair(self, action: str, source_path: str, dest_path: str, keep_original: bool = True) -> dict: ...

    def copy_database(self, source: str, dest: str) -> bool: ...

    def get_table_schema_plan(self) -> tuple[list[TableSchema], UnknownMetadata]: ...
