"""Segregated adapter interfaces — ISP and LSP compliance.

WinComAdapter implements all interfaces. OdbcAdapter implements
IDataAdapter and ISchemaAdapter only.
"""

from typing import Any, Protocol, runtime_checkable
from ..models.database import (
    TableInfo, FormInfo, ReportInfo, MacroInfo, ModuleInfo,
    ControlInfo, RelationshipInfo, QueryInfo,
)
from ..models.migration import TableSchema, UnknownMetadata


@runtime_checkable
class IConnectionManager(Protocol):
    """Minimal lifecycle — connect, disconnect, is_connected."""
    def connect(self, db_path: str) -> bool: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...


@runtime_checkable
class IDataAdapter(IConnectionManager, Protocol):
    """Data CRUD and query execution — ODBC and COM both support this."""
    def execute_query(self, sql: str, params: list | None = None) -> dict: ...
    def insert_data(self, table_name: str, data: dict | list[dict]) -> dict: ...
    def update_data(self, table_name: str, set_dict: dict, where_dict: dict | str | None = None) -> dict: ...
    def delete_data(self, table_name: str, where_dict: dict | str | None = None) -> dict: ...
    def export_data(self, sql: str, file_path: str, format: str = "csv", **options: Any) -> dict: ...
    def execute_raw_sql(self, sql: str) -> int: ...


@runtime_checkable
class ISchemaAdapter(IConnectionManager, Protocol):
    """Schema introspection and DDL — ODBC and COM both support this."""
    def get_tables(self) -> list[TableInfo]: ...
    def get_system_tables(self) -> list[TableInfo]: ...
    def get_object_metadata(self, object_name: str) -> dict: ...
    def get_relationships(self) -> list[RelationshipInfo]: ...
    def get_table_schema_plan(self) -> tuple[list[TableSchema], UnknownMetadata]: ...
    def generate_sql(self, output_path: str) -> dict: ...
    def get_queries(self) -> list[QueryInfo]: ...
    def create_query(self, name: str, sql: str) -> dict: ...
    def set_query_sql(self, name: str, sql: str) -> dict: ...
    def delete_query(self, name: str) -> dict: ...
    def create_table(self, table_name: str, columns: list[dict]) -> dict: ...
    def delete_table(self, table_name: str) -> dict: ...
    def get_linked_tables(self) -> dict: ...
    def create_linked_table(self, name: str, source_table: str, connect_string: str) -> dict: ...
    def refresh_linked_table(self, name: str, connect_string: str | None = None) -> dict: ...
    def recreate_linked_table(self, name: str, source_table: str, connect_string: str, attributes: int | None = None) -> dict: ...
    def unlink_table(self, name: str) -> dict: ...
    def execute_sql_script(self, script_path: str) -> dict: ...


@runtime_checkable
class IUiAdapter(IConnectionManager, Protocol):
    """Access UI automation — COM automation only (WinComAdapter)."""
    def launch_access(self, visible: bool = False) -> None: ...
    def close_access(self) -> None: ...
    def get_forms(self) -> list[FormInfo]: ...
    def get_reports(self) -> list[ReportInfo]: ...
    def get_macros(self) -> list[MacroInfo]: ...
    def get_modules(self) -> list[ModuleInfo]: ...
    def form_exists(self, form_name: str) -> bool: ...
    def report_exists(self, report_name: str) -> bool: ...
    def get_form_controls(self, form_name: str) -> list[ControlInfo]: ...
    def open_form(self, form_name: str) -> bool: ...
    def close_form(self, form_name: str) -> bool: ...
    def delete_form(self, form_name: str) -> bool: ...
    def delete_report(self, report_name: str) -> bool: ...
    def get_control_properties(self, form_name: str, control_name: str) -> dict: ...
    def set_control_property(self, form_name: str, control_name: str, property_name: str, value: str) -> bool: ...
    def set_control_properties(self, form_name: str, control_name: str, properties: dict[str, Any]) -> dict[str, bool]: ...
    def get_control_event_procedures(self, form_name: str, control_name: str) -> list[dict]: ...
    def get_vba_code(self, module_name: str) -> str: ...
    def set_vba_code(self, module_name: str, code: str) -> bool: ...
    def add_vba_procedure(self, module_name: str, procedure_name: str, code: str) -> bool: ...
    def compile_vba(self) -> dict: ...
    def save_database(self) -> dict: ...
    def delete_module(self, module_name: str) -> bool: ...
    def vba_list_procedures(self, module_name: str) -> list[dict]: ...
    def vba_get_procedure(self, module_name: str, procedure_name: str) -> dict: ...
    def vba_replace_procedure(self, module_name: str, procedure_name: str, new_code: str) -> bool: ...
    def export_form_to_text(self, form_name: str) -> str: ...
    def import_form_from_text(self, form_name: str, form_data: str) -> bool: ...
    def export_report_to_text(self, report_name: str) -> str: ...
    def import_report_from_text(self, report_name: str, report_data: str) -> bool: ...
    def export_module_to_text(self, module_name: str) -> str: ...
    def export_macro_to_text(self, macro_name: str) -> str: ...
    def export_all_versioning(self, output_dir: str) -> dict: ...
    def export_query_to_text(self, query_name: str) -> str: ...
    def import_query_from_text(self, query_name: str, query_data: str) -> bool: ...
    def import_all_versioning(self, input_dir: str) -> dict: ...
    def compare_versioning(self, export_dir: str) -> dict: ...
    def export_schema_ddl(self, output_dir: str) -> dict: ...
    def compact_repair(self, action: str, source_path: str, dest_path: str, keep_original: bool = True) -> dict: ...
    def copy_database(self, source: str, dest: str) -> bool: ...