"""Segregated adapter interfaces — ISP and LSP compliance.

WinComAdapter implements all interfaces. OdbcAdapter implements
IDataAdapter, ISchemaAdapter, and IDatabasePropertiesAdapter only.

The UI surface is split into 6 focused protocols (IFormAdapter, IVbaAdapter,
IMacroAdapter, IControlAdapter, IDatabasePropertiesAdapter, IVersioningAdapter).
`IUiAdapter` is retained as a `TypeAlias` combining all six for backward
compatibility with code that previously used the monolithic UI protocol.
"""

from typing import Any, Protocol, TypeAlias, runtime_checkable

from ..models.database import (
    ControlInfo,
    FormInfo,
    IndexInfo,
    MacroInfo,
    ModuleInfo,
    QueryInfo,
    RelationshipInfo,
    ReportInfo,
    TableInfo,
)
from ..models.migration import TableSchema, UnknownMetadata


@runtime_checkable
class IConnectionManager(Protocol):
    """Minimal lifecycle — connect, disconnect, is_connected."""

    def connect(self, db_path: str, password: str = "") -> bool: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...


@runtime_checkable
class IDataAdapter(IConnectionManager, Protocol):
    """Data CRUD and query execution — ODBC and COM both support this."""

    def execute_query(self, sql: str, params: list | None = None) -> dict: ...
    def insert_data(self, table_name: str, data: dict | list[dict]) -> dict: ...
    def update_data(
        self, table_name: str, set_dict: dict, where_dict: dict | str | None = None
    ) -> dict: ...
    def delete_data(self, table_name: str, where_dict: dict | str | None = None) -> dict: ...
    def export_data(
        self, sql: str, file_path: str, format: str = "csv", **options: Any
    ) -> dict: ...
    def execute_raw_sql(self, sql: str) -> int: ...


@runtime_checkable
class ISchemaAdapter(IConnectionManager, Protocol):
    """Schema introspection and DDL — ODBC and COM both support this."""

    def get_tables(self) -> list[TableInfo]: ...
    def get_system_tables(self) -> list[TableInfo]: ...
    def get_object_metadata(self, object_name: str) -> dict: ...
    def get_relationships(self) -> list[RelationshipInfo]: ...
    def get_table_schema_plan(self) -> tuple[list[TableSchema], UnknownMetadata]: ...
    def generate_sql(self, output_path: str) -> dict: ...
    def get_database_statistics(self) -> dict: ...
    def get_queries(self) -> list[QueryInfo]: ...
    def create_query(self, name: str, sql: str) -> dict: ...
    def set_query_sql(self, name: str, sql: str) -> dict: ...
    def delete_query(self, name: str) -> dict: ...
    def create_table(self, table_name: str, columns: list[dict]) -> dict: ...
    def delete_table(self, table_name: str) -> dict: ...
    def get_linked_tables(self) -> dict: ...
    def create_linked_table(self, name: str, source_table: str, connect_string: str) -> dict: ...
    def refresh_linked_table(self, name: str, connect_string: str | None = None) -> dict: ...
    def recreate_linked_table(
        self, name: str, source_table: str, connect_string: str, attributes: int | None = None
    ) -> dict: ...
    def unlink_table(self, name: str) -> dict: ...
    def execute_sql_script(self, script_path: str) -> dict: ...
    def alter_table(self, table_name: str, operations: list[dict]) -> dict: ...
    def get_indexes(self, table_name: str) -> list[IndexInfo]: ...
    def create_index(
        self,
        table_name: str,
        index_name: str,
        columns: list[str],
        unique: bool = False,
        ignore_nulls: bool = False,
    ) -> dict: ...
    def drop_index(self, table_name: str, index_name: str) -> dict: ...
    def create_relationship(
        self,
        table_name: str,
        relationship_name: str,
        columns: list[str],
        foreign_table: str,
        foreign_columns: list[str],
    ) -> dict: ...
    def delete_relationship(self, table_name: str, relationship_name: str) -> dict: ...


# ========================================================================
# Segregated UI protocols (Interface Segregation Principle split)
# Each Protocol is small and focused. WinComAdapter implements all six.
# OdbcAdapter implements IDatabasePropertiesAdapter (with NotImplementedError
# stubs) and the rest of the UI surface is provided by ComOnlyAdapterMixin.
# ========================================================================


@runtime_checkable
class IFormAdapter(Protocol):
    """Form-level operations — open/close, controls, properties, sections.

    Backed by Access COM automation. ODBC cannot read form definitions.
    """

    def get_forms(self) -> list[FormInfo]: ...
    def form_exists(self, form_name: str) -> bool: ...
    def create_form(
        self,
        form_name: str,
        record_source: str = "",
        template_name: str = "",
        properties: dict[str, Any] | None = None,
    ) -> bool: ...
    def rename_form(self, old_name: str, new_name: str) -> bool: ...
    def delete_form(self, form_name: str) -> bool: ...
    def open_form(self, form_name: str) -> bool: ...
    def close_form(self, form_name: str) -> bool: ...
    def get_form_properties(self, form_name: str) -> dict: ...
    def set_form_property(self, form_name: str, property_name: str, value: str) -> bool: ...
    def set_form_properties(
        self, form_name: str, properties: dict[str, Any]
    ) -> dict[str, bool]: ...
    def get_form_sections(self, form_name: str) -> list: ...
    def get_form_section_properties(self, form_name: str, section_id: int) -> dict: ...
    def set_form_section_property(
        self, form_name: str, section_id: int, property_name: str, value: str
    ) -> bool: ...
    def set_form_section_properties(
        self, form_name: str, section_id: int, properties: dict[str, Any]
    ) -> dict[str, bool]: ...
    # Reports (grouped with forms because they share lifecycle and property model)
    def get_reports(self) -> list[ReportInfo]: ...
    def report_exists(self, report_name: str) -> bool: ...
    def create_report(
        self,
        report_name: str,
        record_source: str = "",
        template_name: str = "",
        properties: dict[str, Any] | None = None,
    ) -> bool: ...
    def rename_report(self, old_name: str, new_name: str) -> bool: ...
    def delete_report(self, report_name: str) -> bool: ...
    def get_report_properties(self, report_name: str) -> dict: ...
    def set_report_property(self, report_name: str, property_name: str, value: str) -> bool: ...
    def set_report_properties(
        self, report_name: str, properties: dict[str, Any]
    ) -> dict[str, bool]: ...
    def get_report_sections(self, report_name: str) -> list: ...
    def get_report_section_properties(self, report_name: str, section_id: int) -> dict: ...
    def set_report_section_property(
        self, report_name: str, section_id: int, property_name: str, value: str
    ) -> bool: ...
    def set_report_section_properties(
        self, report_name: str, section_id: int, properties: dict[str, Any]
    ) -> dict[str, bool]: ...
    # Form / report text export-import pipeline
    def export_form_to_text(self, form_name: str) -> str: ...
    def import_form_from_text(self, form_name: str, form_data: str) -> bool: ...
    def export_report_to_text(self, report_name: str) -> str: ...
    def import_report_from_text(self, report_name: str, report_data: str) -> bool: ...
    # Spec-named form helpers
    def get_form_controls(self, form_name: str) -> list[ControlInfo]: ...
    def export_form_to_html(self, form_name: str) -> str: ...
    def get_control_property(
        self, form_name: str, control_name: str, property_name: str
    ) -> Any: ...
    def set_control_property(
        self, form_name: str, control_name: str, property_name: str, value: str
    ) -> bool: ...


@runtime_checkable
class IVbaAdapter(Protocol):
    """VBA module operations — read, write, compile, list procedures.

    Backed by Access COM automation. ODBC cannot touch VBA project.
    """

    def get_modules(self) -> list[ModuleInfo]: ...
    def module_exists(self, module_name: str) -> bool: ...
    def create_module(self, module_name: str, module_type: int = 1) -> bool: ...
    def delete_module(self, module_name: str) -> bool: ...
    def rename_module(self, old_name: str, new_name: str) -> bool: ...
    def get_vba_code(self, module_name: str) -> str: ...
    def set_vba_code(self, module_name: str, code: str) -> bool: ...
    def add_vba_procedure(self, module_name: str, procedure_name: str, code: str) -> bool: ...
    def compile_vba(self) -> dict: ...
    def save_database(self) -> dict: ...
    def vba_list_procedures(self, module_name: str) -> list[dict]: ...
    def vba_get_procedure(self, module_name: str, procedure_name: str) -> dict: ...
    def vba_replace_procedure(
        self, module_name: str, procedure_name: str, new_code: str
    ) -> bool: ...
    def export_module_to_text(self, module_name: str) -> str: ...
    # Spec-named VBA helpers (aliasing the canonical methods above)
    def get_vba_module(self, module_name: str) -> str: ...
    def save_vba_module(self, module_name: str, code: str) -> bool: ...
    def execute_vba(self, function_name: str, *args: Any) -> Any: ...
    def get_vba_references(self) -> list[dict]: ...
    def add_vba_reference(self, reference_path: str) -> bool: ...


@runtime_checkable
class IMacroAdapter(Protocol):
    """Macro lifecycle — list, create, rename, delete, run.

    Backed by Access COM automation. ODBC cannot enumerate macros.
    """

    def get_macros(self) -> list[MacroInfo]: ...
    def macro_exists(self, macro_name: str) -> bool: ...
    def create_macro(self, macro_name: str) -> bool: ...
    def rename_macro(self, old_name: str, new_name: str) -> bool: ...
    def delete_macro(self, macro_name: str) -> bool: ...
    def run_macro(self, macro_name: str) -> bool: ...
    def get_macro_properties(self, macro_name: str) -> dict: ...
    def export_macro_to_text(self, macro_name: str) -> str: ...


@runtime_checkable
class IControlAdapter(Protocol):
    """Control-level operations on forms/reports.

    Backed by Access COM automation. ODBC cannot manipulate UI controls.
    """

    def add_control(
        self,
        form_name: str,
        control_type: str,
        control_name: str,
        section: int = 0,
        properties: dict[str, Any] | None = None,
    ) -> bool: ...
    def remove_control(self, form_name: str, control_name: str) -> bool: ...
    def set_control_property(
        self, form_name: str, control_name: str, property_name: str, value: str
    ) -> bool: ...
    def set_control_properties(
        self, form_name: str, control_name: str, properties: dict[str, Any]
    ) -> dict[str, bool]: ...
    def get_control_properties(self, form_name: str, control_name: str) -> dict: ...
    def get_control_event_procedures(self, form_name: str, control_name: str) -> list[dict]: ...
    def set_control_event_procedure(
        self, form_name: str, control_name: str, event_name: str, code: str
    ) -> bool: ...
    def add_report_control(
        self,
        report_name: str,
        control_type: str,
        control_name: str,
        section: int = 0,
        properties: dict[str, Any] | None = None,
    ) -> bool: ...
    def remove_report_control(self, report_name: str, control_name: str) -> bool: ...
    def get_report_controls(self, report_name: str) -> list[ControlInfo]: ...
    def get_report_control_properties(self, report_name: str, control_name: str) -> dict: ...
    def set_report_control_property(
        self, report_name: str, control_name: str, property_name: str, value: str
    ) -> bool: ...
    def set_report_control_properties(
        self, report_name: str, control_name: str, properties: dict[str, Any]
    ) -> dict[str, bool]: ...
    # Spec-named control helpers
    def get_controls(self, form_name: str) -> list[ControlInfo]: ...
    def get_control_property(
        self, form_name: str, control_name: str, property_name: str
    ) -> Any: ...
    def set_control_source(
        self, form_name: str, control_name: str, source: str
    ) -> bool: ...


@runtime_checkable
class IDatabasePropertiesAdapter(Protocol):
    """DAO CurrentDb.Properties read/write.

    WinComAdapter implements this via COM. OdbcAdapter declares it
    (raising NotImplementedError) so services can type-hint against
    IDatabasePropertiesAdapter uniformly.
    """

    def get_database_properties(self, names: list[str] | None = None) -> dict: ...
    def set_database_property(
        self, name: str, value: str, type: str | None = None
    ) -> bool: ...


@runtime_checkable
class IVersioningAdapter(Protocol):
    """Database versioning / backup / restore / export.

    WinComAdapter implements the full surface. OdbcAdapter does NOT
    implement this protocol — the methods are present as extra
    convenience methods only for AccessAdapter backward compatibility.
    """

    def export_all_versioning(self, output_dir: str) -> dict: ...
    def import_all_versioning(self, input_dir: str) -> dict: ...
    def compare_versioning(self, export_dir: str) -> dict: ...
    def export_schema_ddl(self, output_dir: str) -> dict: ...
    def export_query_to_text(self, query_name: str) -> str: ...
    def import_query_from_text(self, query_name: str, query_data: str) -> bool: ...
    def compact_repair(
        self, action: str, source_path: str, dest_path: str, keep_original: bool = True
    ) -> dict: ...
    def copy_database(self, source: str, dest: str) -> bool: ...
    # Spec-named versioning helpers (aliasing the canonical methods above)
    def export_database(self, output_dir: str) -> dict: ...
    def import_database(self, input_dir: str) -> dict: ...
    def create_backup(self, source_path: str, backup_path: str) -> bool: ...
    def restore_backup(self, backup_path: str, dest_path: str) -> bool: ...


# ========================================================================
# Backward-compat composite alias — IUiAdapter is the union of the 6
# focused UI protocols. Existing code that imported IUiAdapter keeps
# working; new code should import the focused protocol it actually needs.
# ========================================================================

IUiAdapter: TypeAlias = (
    IFormAdapter | IVbaAdapter | IMacroAdapter | IControlAdapter
    | IDatabasePropertiesAdapter | IVersioningAdapter
)
