"""
Integration tests for MigrationService — schema extraction, upload, and transfer.

Requires:
  - Windows OS with MS Access installed
  - pywin32 (win32com.client)
  - A test .accdb database file (generated by generate_fixture.py)

Marked: com_integration

Usage:
  pytest tests/integration/test_migration.py -m com_integration -v
  ACCESS_TEST_DB=D:/path/to/test.accdb pytest tests/integration/test_migration.py -m com_integration -v
"""

import os
import sqlite3
import pytest

from helpers import (
    skip_unless_windows,
    skip_unless_pywin32,
    skip_unless_db,
    TEST_DB,
)
from generate_fixture import OUTPUT_PATH as _FIXTURE_DB_PATH
FIXTURE_DB = str(_FIXTURE_DB_PATH)

pytestmark = [pytest.mark.com_integration, skip_unless_windows, skip_unless_pywin32, skip_unless_db]

ALL_TABLES = ["customers", "orders", "products", "type_test"]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def temp_sqlite_db(tmp_path):
    """Provide a temporary SQLite database path, cleaned up after test."""
    db_path = tmp_path / "test_migrate.db"
    yield str(db_path)
    if db_path.exists():
        db_path.unlink()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_sqlite_tables(sqlite_path: str) -> list[str]:
    """Return sorted table names in an SQLite database."""
    conn = sqlite3.connect(sqlite_path)
    cur = conn.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
    names = [row[0] for row in cur.fetchall()]
    conn.close()
    return names


def _get_sqlite_counts(sqlite_path: str) -> dict[str, int]:
    """Return {table: row_count} for ALL_TABLES from an SQLite database."""
    conn = sqlite3.connect(sqlite_path)
    cur = conn.cursor()
    counts = {}
    for table in ALL_TABLES:
        cur.execute(f'SELECT COUNT(*) FROM "{table}"')
        counts[table] = cur.fetchone()[0]
    conn.close()
    return counts


def _get_access_counts(adapter) -> dict[str, int]:
    """Return {table: row_count} for ALL_TABLES from Access via adapter."""
    counts = {}
    for table in ALL_TABLES:
        result = adapter.execute_query(f"SELECT COUNT(*) AS cnt FROM [{table}]")
        assert result["success"] is True, f"Query failed for {table}: {result.get('error')}"
        rows = result["rows"]
        counts[table] = rows[0]["cnt"] if rows else 0
    return counts


def _assert_sqlite_tables_exist(sqlite_path: str, expected: list[str] | None = None) -> None:
    """Assert that all expected tables exist in the SQLite database."""
    expected = expected or ALL_TABLES
    table_names = _get_sqlite_tables(sqlite_path)
    for name in expected:
        assert name in table_names, f"Table '{name}' missing from SQLite"


def _run_full_pipeline(service, adapter, tmp_path) -> tuple[str, str]:
    """Run extract → upload → transfer pipeline, return (sqlite_path, job_id)."""
    schema = service.extract_schema(adapter, FIXTURE_DB)
    sqlite_path = str(tmp_path / "transfer_target.db")
    upload_result = service.upload_schema("sqlite", sqlite_path, schema)
    assert upload_result["success"] is True, f"Schema upload failed: {upload_result}"
    result = service.transfer_data("sqlite", sqlite_path, schema, adapter)
    assert result["success"] is True, f"Transfer failed: {result.get('error', 'unknown')}"
    return sqlite_path, result["job_id"]


# ---------------------------------------------------------------------------
# Base test class
# ---------------------------------------------------------------------------


class _MigrationTestBase:
    """Shared setup/teardown for all migration test classes.

    Each class creates its own WinComAdapter + MigrationService pair to avoid
    carrying connection state across class boundaries.
    """

    def setup_method(self):
        from ms_access_mcp.adapters.wincom import WinComAdapter
        from ms_access_mcp.services.migration import MigrationService

        self.adapter = WinComAdapter()
        assert self.adapter.connect(FIXTURE_DB), f"Failed to connect to {FIXTURE_DB}"
        self.service = MigrationService()

    def teardown_method(self):
        self.adapter.disconnect()


# ---------------------------------------------------------------------------
# Extract Schema tests
# ---------------------------------------------------------------------------


class TestExtractSchema(_MigrationTestBase):
    """Tests for MigrationService.extract_schema()."""

    def test_extract_schema_returns_all_tables(self):
        """Full schema extraction includes customers, orders, products, type_test."""
        schema = self.service.extract_schema(self.adapter, FIXTURE_DB)
        table_names = [t.name for t in schema.tables]
        for name in ALL_TABLES:
            assert name in table_names

    def test_extract_schema_each_table_has_columns(self):
        """Each table has correct column names."""
        schema = self.service.extract_schema(self.adapter, FIXTURE_DB)
        table_by_name = {t.name: t for t in schema.tables}

        # customers table
        cust_cols = [c.name for c in table_by_name["customers"].columns]
        assert "ID" in cust_cols
        assert "Name" in cust_cols

        # orders table
        ord_cols = [c.name for c in table_by_name["orders"].columns]
        assert "ID" in ord_cols
        assert "CustomerID" in ord_cols
        assert "Total" in ord_cols

        # type_test table — all 9 column types
        type_cols = [c.name for c in table_by_name["type_test"].columns]
        for col in ("ID", "name", "active", "created", "price", "notes", "guid", "rating", "level"):
            assert col in type_cols

    @pytest.mark.skip(reason="Service does not populate primary_key yet")
    def test_extract_schema_primary_key_detected(self):
        """ID column is detected as primary key for extracted tables."""
        schema = self.service.extract_schema(self.adapter, FIXTURE_DB)
        table_by_name = {t.name: t for t in schema.tables}
        assert "ID" in table_by_name["customers"].primary_key
        assert "ID" in table_by_name["type_test"].primary_key

    def test_extract_schema_idempotent(self):
        """Calling extract_schema twice returns equivalent results."""
        schema1 = self.service.extract_schema(self.adapter, FIXTURE_DB)
        schema2 = self.service.extract_schema(self.adapter, FIXTURE_DB)

        names1 = sorted(t.name for t in schema1.tables)
        names2 = sorted(t.name for t in schema2.tables)
        assert names1 == names2

        for t1, t2 in zip(schema1.tables, schema2.tables):
            cols1 = sorted(c.name for c in t1.columns)
            cols2 = sorted(c.name for c in t2.columns)
            assert cols1 == cols2


# ---------------------------------------------------------------------------
# Upload Schema tests
# ---------------------------------------------------------------------------


class TestUploadSchema(_MigrationTestBase):
    """Tests for MigrationService.upload_schema() with SQLite target."""

    def setup_method(self):
        super().setup_method()
        self.schema = self.service.extract_schema(self.adapter, FIXTURE_DB)

    def test_upload_creates_sqlite_tables(self, temp_sqlite_db):
        """Upload creates all expected tables in SQLite DB."""
        result = self.service.upload_schema("sqlite", temp_sqlite_db, self.schema)
        assert result["success"] is True
        _assert_sqlite_tables_exist(temp_sqlite_db)

    def test_upload_column_types_map_correctly(self, temp_sqlite_db):
        """Column types map correctly: Boolean→INTEGER, Date/Time→TEXT, Currency→REAL, Memo→TEXT, GUID→TEXT."""
        self.service.upload_schema("sqlite", temp_sqlite_db, self.schema)

        conn = sqlite3.connect(temp_sqlite_db)
        cur = conn.cursor()
        cur.execute(f'PRAGMA table_info("type_test")')
        columns = {row[1]: row[2] for row in cur.fetchall()}
        conn.close()

        # ID — Long Integer → INTEGER
        assert columns["ID"] == "INTEGER"
        # name — Text → TEXT
        assert columns["name"] == "TEXT"
        # active — Boolean → INTEGER
        assert columns["active"] == "INTEGER"
        # created — Date/Time → TEXT
        assert columns["created"] == "TEXT"
        # price — Currency → REAL
        assert columns["price"] == "REAL"
        # notes — Memo → TEXT
        assert columns["notes"] == "TEXT"
        # guid — GUID → TEXT
        assert columns["guid"] == "TEXT"
        # rating — Double → REAL
        assert columns["rating"] == "REAL"
        # level — Byte → INTEGER
        assert columns["level"] == "INTEGER"

    def test_upload_existing_table_reported_in_failed(self, temp_sqlite_db):
        """Upload with already-existing table reports it in tables_failed (no duplicates)."""
        # First upload — should succeed
        result1 = self.service.upload_schema("sqlite", temp_sqlite_db, self.schema)
        assert result1["success"] is True
        tables_created = set(result1["tables_created"])

        # Second upload — existing tables should be in tables_failed
        result2 = self.service.upload_schema("sqlite", temp_sqlite_db, self.schema)
        assert result2["success"] is True
        assert len(result2["tables_created"]) == 0
        assert set(result2["tables_failed"]) == tables_created


# ---------------------------------------------------------------------------
# Transfer Data tests
# ---------------------------------------------------------------------------


class TestTransferData(_MigrationTestBase):
    """Tests for MigrationService.transfer_data() with SQLite target."""

    def setup_method(self):
        super().setup_method()
        self.schema = self.service.extract_schema(self.adapter, FIXTURE_DB)

    def test_transfer_row_counts_match_access(self, tmp_path):
        """SQLite row counts match Access row counts for all tables."""
        sqlite_path, _ = _run_full_pipeline(self.service, self.adapter, tmp_path)

        access_counts = _get_access_counts(self.adapter)
        sqlite_counts = _get_sqlite_counts(sqlite_path)

        for table in ALL_TABLES:
            assert sqlite_counts[table] == access_counts[table], (
                f"{table}: SQLite has {sqlite_counts[table]}, Access has {access_counts[table]}"
            )

    def test_transfer_values_preserved(self, tmp_path):
        """Representative rows preserve NULLs, booleans, currency, datetime, GUIDs, numeric values."""
        sqlite_path, _ = _run_full_pipeline(self.service, self.adapter, tmp_path)

        conn = sqlite3.connect(sqlite_path)
        cur = conn.cursor()
        cur.execute('SELECT name, active, created, price, notes, guid, rating, level FROM "type_test" ORDER BY ID')
        rows = cur.fetchall()
        conn.close()

        assert len(rows) >= 1, "type_test should have at least 1 row after transfer"

        for row in rows:
            name, active, created, price, notes, guid, rating, level = row
            if name is not None:
                assert isinstance(name, str)
            if active is not None:
                assert active in (0, 1), f"Expected boolean int, got {type(active).__name__}={active}"
            if created is not None:
                assert isinstance(created, str) and len(created) > 0
            if price is not None:
                assert isinstance(price, float)
            if notes is not None:
                assert isinstance(notes, str)
            if guid is not None:
                assert isinstance(guid, str) and len(guid) > 0
            if rating is not None:
                assert isinstance(rating, float)
            if level is not None:
                assert isinstance(level, int)

    def test_get_job_status_completed(self, tmp_path):
        """Completed job has status='completed', progress=1.0, and per-table results."""
        sqlite_path, job_id = _run_full_pipeline(self.service, self.adapter, tmp_path)

        status = self.service.get_job_status(job_id)
        assert status["success"] is True
        job = status["job"]

        assert job["status"] == "completed"
        assert job["progress"] == 1.0
        assert len(job["results"]) == 4

        result_tables = {r["table"] for r in job["results"]}
        assert result_tables == set(ALL_TABLES)

        for r in job["results"]:
            assert r["success"] is True, f"Table {r['table']} failed: {r.get('error')}"

    def test_extract_schema_disconnected_adapter_returns_empty(self):
        """Calling extract_schema with disconnected adapter returns empty schema (no error raised)."""
        from ms_access_mcp.adapters.wincom import WinComAdapter
        from ms_access_mcp.services.migration import MigrationService

        disconnected_adapter = WinComAdapter()
        assert not disconnected_adapter.is_connected()
        service = MigrationService()

        schema = service.extract_schema(disconnected_adapter, FIXTURE_DB)
        assert len(schema.tables) == 0

    def test_upload_schema_invalid_path(self):
        """upload_schema with non-existent parent directory returns success=False."""
        invalid_path = "Z:/nonexistent/path/that/does/not/exist/maybe/no_perms/test.db"
        result = self.service.upload_schema("sqlite", invalid_path, self.schema)
        assert result["success"] is False
        assert "tables_created" in result
        assert "tables_failed" in result

    def test_transfer_data_invalid_path(self):
        """transfer_data with non-existent directory returns success=False and connector error."""
        invalid_path = "Z:/nonexistent/path/that/does/not/exist/maybe/no_perms/test.db"
        result = self.service.transfer_data("sqlite", invalid_path, self.schema, self.adapter)
        assert result["success"] is False
        assert "job_id" in result
        assert "error" in result