// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Odbc from "odbc";
import * as Errors from "../Errors.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";

function mapNativeError(message, code, state) {
  return Errors.databaseError(code !== undefined ? (
      state !== undefined ? message + " [SQLSTATE " + state + ", " + code + "]" : message + " [" + code + "]"
    ) : (
      state !== undefined ? message + " [SQLSTATE " + state + "]" : message
    ));
}

function exnMessage(e) {
  let raw = (e => e && typeof e.message === 'string' ? e.message : null)(e);
  if (raw !== undefined) {
    return raw;
  } else {
    return "Unknown error";
  }
}

function connect(connectionString) {
  return Stdlib_Promise.$$catch(Odbc.import().then(m => {
    let rawDefault = m["default"];
    let rawMod = rawDefault !== undefined ? rawDefault : (m => m)(m);
    return Stdlib_Promise.$$catch(rawMod.connect(connectionString).then(conn => {
      let c_query = (sql, params) => Stdlib_Promise.$$catch(conn.query(sql, params).then(r => Promise.resolve({
        TAG: "Ok",
        _0: r
      })), e => {
        let msg = exnMessage(e);
        return Promise.resolve({
          TAG: "Error",
          _0: mapNativeError(msg, undefined, undefined)
        });
      });
      let c_tables = (catalog, schema, table, tableType) => Stdlib_Promise.$$catch(conn.tables(catalog, schema, table, tableType).then(rows => Promise.resolve({
        TAG: "Ok",
        _0: rows
      })), e => {
        let msg = exnMessage(e);
        return Promise.resolve({
          TAG: "Error",
          _0: mapNativeError(msg, undefined, undefined)
        });
      });
      let c_columns = (catalog, schema, table, column) => Stdlib_Promise.$$catch(conn.columns(catalog, schema, table, column).then(rows => Promise.resolve({
        TAG: "Ok",
        _0: rows
      })), e => {
        let msg = exnMessage(e);
        return Promise.resolve({
          TAG: "Error",
          _0: mapNativeError(msg, undefined, undefined)
        });
      });
      let c_close = () => conn.close();
      let c = {
        query: c_query,
        tables: c_tables,
        columns: c_columns,
        close: c_close
      };
      return Promise.resolve({
        TAG: "Ok",
        _0: c
      });
    }), e => {
      let msg = exnMessage(e);
      return Promise.resolve({
        TAG: "Error",
        _0: mapNativeError(msg, undefined, undefined)
      });
    });
  }), e => {
    let msg = exnMessage(e);
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError(msg)
    });
  });
}

function valueToJson(v) {
  if (typeof v !== "object") {
    return null;
  }
  switch (v.TAG) {
    case "Int" :
    case "Float" :
      return v._0;
    case "Bool" :
      return v._0 ? 1.0 : 0.0;
    case "Str" :
      return v._0;
    case "DateTime" :
      return v._0.toISOString();
    case "Buffer" :
      let encoded = (b => b && typeof b.toString === 'function' ? b.toString('base64') : '')(v._0);
      return encoded;
  }
}

function jsonToValue(j) {
  if (j === null) {
    return null;
  }
  if (Array.isArray(j)) {
    return j;
  }
  switch (typeof j) {
    case "boolean" :
      return j ? 1.0 : 0.0;
    case "string" :
      return j;
    case "number" :
      return j;
    case "object" :
      return j;
  }
}

function odbc(prim) {
  return Odbc.import();
}

export {
  connect,
  mapNativeError,
  valueToJson,
  jsonToValue,
  odbc,
}
/* odbc Not a pure module */
