// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Odbc from "../Bindings/Odbc.res.mjs";
import * as Errors from "../Errors.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as SqlBuilder from "./SqlBuilder.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";

function _exnMessage(e) {
  let raw = (e => e && typeof e.message === 'string' ? e.message : null)(e);
  if (raw !== undefined) {
    return raw;
  } else {
    return "Unknown error";
  }
}

function _normalizeQueryResult(result) {
  let jsonRows = Belt_Array.map(result.rows, row => {
    let entries = (d => Object.entries(d))(row);
    return (entries => Object.fromEntries(entries))(Belt_Array.map(entries, param => [
      param[0],
      Odbc.valueToJson(param[1])
    ]));
  });
  return {
    success: true,
    rows: jsonRows,
    count: result.count,
    columns: result.columns,
    error: undefined
  };
}

function _normalizeMutationResult(result) {
  return {
    success: true,
    affected: result.count,
    error: undefined
  };
}

function connect(adapter, connectionString, password) {
  let connStrWithPwd = password !== undefined ? connectionString + ";PWD=" + password : connectionString;
  return Stdlib_Promise.$$catch(Odbc.connect(connStrWithPwd).then(result => {
    if (result.TAG !== "Ok") {
      return Promise.resolve({
        TAG: "Error",
        _0: result._0
      });
    }
    adapter.connection = result._0;
    return Promise.resolve({
      TAG: "Ok",
      _0: true
    });
  }), e => {
    let msg = _exnMessage(e);
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError(msg)
    });
  });
}

function disconnect(adapter) {
  let conn = adapter.connection;
  if (conn !== undefined) {
    return Stdlib_Promise.$$catch(conn.close().then(() => {
      adapter.connection = undefined;
      return Promise.resolve({
        TAG: "Ok",
        _0: undefined
      });
    }), e => {
      adapter.connection = undefined;
      let msg = _exnMessage(e);
      return Promise.resolve({
        TAG: "Error",
        _0: Errors.databaseError(msg)
      });
    });
  } else {
    return Promise.resolve({
      TAG: "Ok",
      _0: undefined
    });
  }
}

function isConnected(adapter) {
  return Promise.resolve({
    TAG: "Ok",
    _0: adapter.connection !== undefined
  });
}

function _requireConnection(adapter) {
  return adapter.connection;
}

function _buildWhereClause(whereOpt) {
  if (whereOpt === undefined) {
    return;
  }
  if (typeof whereOpt !== "object" || whereOpt === null || Array.isArray(whereOpt)) {
    return;
  }
  let dictEntry = whereOpt["Dict"];
  let rawEntry = whereOpt["Raw"];
  let exit = 0;
  if (dictEntry !== undefined) {
    if (typeof dictEntry === "object" && dictEntry !== null && !Array.isArray(dictEntry)) {
      return {
        TAG: "Dict",
        _0: dictEntry
      };
    }
    exit = 2;
  } else {
    exit = 2;
  }
  if (exit === 2 && typeof rawEntry === "string") {
    return {
      TAG: "Raw",
      _0: rawEntry
    };
  }
  if (dictEntry === undefined) {
    return;
  }
  if (typeof dictEntry !== "string") {
    return;
  }
  let d = (k => ({[k]: null}))(dictEntry);
  return {
    TAG: "Dict",
    _0: d
  };
}

function executeQuery(adapter, sql, params) {
  let conn = adapter.connection;
  if (conn === undefined) {
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError("Not connected")
    });
  }
  let queryParams = params !== undefined ? params : [];
  return Stdlib_Promise.$$catch(conn.query(sql, queryParams).then(result => {
    if (result.TAG === "Ok") {
      return Promise.resolve({
        TAG: "Ok",
        _0: _normalizeQueryResult(result._0)
      });
    } else {
      return Promise.resolve({
        TAG: "Error",
        _0: result._0
      });
    }
  }), e => {
    let msg = _exnMessage(e);
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError(msg)
    });
  });
}

function insertData(adapter, table, record) {
  let conn = adapter.connection;
  if (conn === undefined) {
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError("Not connected")
    });
  }
  let match = SqlBuilder.insert(table, record);
  return Stdlib_Promise.$$catch(conn.query(match[0], match[1]).then(result => {
    if (result.TAG === "Ok") {
      return Promise.resolve({
        TAG: "Ok",
        _0: _normalizeMutationResult(result._0)
      });
    } else {
      return Promise.resolve({
        TAG: "Error",
        _0: result._0
      });
    }
  }), e => {
    let msg = _exnMessage(e);
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError(msg)
    });
  });
}

function updateData(adapter, table, setDict, where) {
  let conn = adapter.connection;
  if (conn === undefined) {
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError("Not connected")
    });
  }
  let whereOpt = _buildWhereClause(where);
  let match = SqlBuilder.update(table, setDict, whereOpt);
  return Stdlib_Promise.$$catch(conn.query(match[0], match[1]).then(result => {
    if (result.TAG === "Ok") {
      return Promise.resolve({
        TAG: "Ok",
        _0: _normalizeMutationResult(result._0)
      });
    } else {
      return Promise.resolve({
        TAG: "Error",
        _0: result._0
      });
    }
  }), e => {
    let msg = _exnMessage(e);
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError(msg)
    });
  });
}

function deleteData(adapter, table, where) {
  let conn = adapter.connection;
  if (conn === undefined) {
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError("Not connected")
    });
  }
  let whereOpt = _buildWhereClause(where);
  let match = SqlBuilder.$$delete(table, whereOpt);
  return Stdlib_Promise.$$catch(conn.query(match[0], match[1]).then(result => {
    if (result.TAG === "Ok") {
      return Promise.resolve({
        TAG: "Ok",
        _0: _normalizeMutationResult(result._0)
      });
    } else {
      return Promise.resolve({
        TAG: "Error",
        _0: result._0
      });
    }
  }), e => {
    let msg = _exnMessage(e);
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError(msg)
    });
  });
}

function executeRawSql(adapter, sql) {
  let conn = adapter.connection;
  if (conn !== undefined) {
    return Stdlib_Promise.$$catch(conn.query(sql, []).then(result => {
      if (result.TAG === "Ok") {
        return Promise.resolve({
          TAG: "Ok",
          _0: result._0.count
        });
      } else {
        return Promise.resolve({
          TAG: "Error",
          _0: result._0
        });
      }
    }), e => {
      let msg = _exnMessage(e);
      return Promise.resolve({
        TAG: "Error",
        _0: Errors.databaseError(msg)
      });
    });
  } else {
    return Promise.resolve({
      TAG: "Error",
      _0: Errors.databaseError("Not connected")
    });
  }
}

function exportData(_adapter, _table, _filePath, _format, _options) {
  return Promise.resolve({
    TAG: "Error",
    _0: Errors.databaseError("exportData not yet implemented")
  });
}

export {
  _exnMessage,
  _normalizeQueryResult,
  _normalizeMutationResult,
  connect,
  disconnect,
  isConnected,
  _requireConnection,
  _buildWhereClause,
  executeQuery,
  insertData,
  updateData,
  deleteData,
  executeRawSql,
  exportData,
}
/* Odbc Not a pure module */
