// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Odbc from "../src/Bindings/Odbc.res.mjs";
import * as Test from "rescript-test/src/Test.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

Test.test("OdbcValue can represent Null", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("OdbcValue can represent Int", () => Test.assertion(undefined, "equal", (a, b) => a === b, 42, 42));

Test.test("OdbcValue can represent Float", () => Test.assertion(undefined, "equal", (a, b) => a === b, 3.14, 3.14));

Test.test("OdbcValue can represent Bool", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("OdbcValue can represent Str", () => Test.assertion(undefined, "equal", (a, b) => a === b, "hello", "hello"));

Test.test("OdbcRow type is constructible with string:OdbcValue pairs", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("OdbcResult can be constructed with rows, columns, count", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, 0, 0);
  Test.assertion(undefined, "equal", Primitive_object.equal, undefined, undefined);
});

Test.test("OdbcResult statement is option<string>", () => {
  let result_rows = [];
  let result_columns = [
    "id",
    "name"
  ];
  let result_statement = "SELECT id, name FROM Products";
  Test.assertion(undefined, "equal", Primitive_object.equal, result_columns, [
    "id",
    "name"
  ]);
  Test.assertion(undefined, "equal", (a, b) => a === b, 2, 2);
});

Test.test("OdbcError can be constructed with message only", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, "Connection failed", "Connection failed");
  Test.assertion(undefined, "equal", Primitive_object.equal, undefined, undefined);
});

Test.test("OdbcError can be constructed with code and state", () => {
  Test.assertion(undefined, "equal", Primitive_object.equal, "S0002", "S0002");
  Test.assertion(undefined, "equal", Primitive_object.equal, "42S02", "42S02");
});

Test.test("CONNECTION module type exists and is accessible", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("connect function type signature returns Promise.t", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("mapNativeError produces an Errors.DatabaseError", () => {
  let err = Odbc.mapNativeError("Table not found", undefined, undefined);
  if (err.TAG === "DatabaseError") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, err._0, "Table not found");
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  }
});

Test.test("mapNativeError folds code into message when present", () => {
  let err = Odbc.mapNativeError("Syntax error", "S0001", undefined);
  if (err.TAG === "DatabaseError") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, err._0.includes("S0001"), true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  }
});

Test.test("mapNativeError folds state into message when present", () => {
  let err = Odbc.mapNativeError("Error", undefined, "S0002");
  if (err.TAG === "DatabaseError") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, err._0.includes("S0002"), true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  }
});

Test.test("valueToJson: Null maps to JSON.Null", () => {
  let j = Odbc.valueToJson("Null");
  if (j === null) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  }
});

Test.test("valueToJson: Int maps to Number", () => {
  let j = Odbc.valueToJson({
    TAG: "Int",
    _0: 99
  });
  if (typeof j === "number") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, j | 0, 99);
  }
  Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
});

Test.test("valueToJson: Float maps to Number", () => {
  let j = Odbc.valueToJson({
    TAG: "Float",
    _0: 1.5
  });
  if (typeof j === "number") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, j, 1.5);
  }
  Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
});

Test.test("valueToJson: Bool maps to Number (1.0/0.0)", () => {
  let jT = Odbc.valueToJson({
    TAG: "Bool",
    _0: true
  });
  let jF = Odbc.valueToJson({
    TAG: "Bool",
    _0: false
  });
  if (jT === 1.0 && jF === 0.0) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
  Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
});

Test.test("valueToJson: Str maps to String", () => {
  let j = Odbc.valueToJson({
    TAG: "Str",
    _0: "test"
  });
  if (typeof j === "string") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, j, "test");
  }
  Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
});

Test.test("jsonToValue: JSON.Null stays Null", () => {
  let v = Odbc.jsonToValue(null);
  if (v === null) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  }
});

Test.test("jsonToValue: JSON.String passes through", () => {
  let v = Odbc.jsonToValue("hello");
  if (typeof v === "string") {
    return Test.assertion(undefined, "equal", (a, b) => a === b, v, "hello");
  }
  Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
});

Test.test("Bindings module exposes only the defined externals and types", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

/*  Not a pure module */
