// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

Test.test("TableInfo record can be constructed and fields accessed", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, "Orders", "Orders");
  Test.assertion(undefined, "equal", (a, b) => a === b, 0, 0);
});

Test.test("FieldInfo record can be constructed with all fields", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, "OrderID", "OrderID");
  Test.assertion(undefined, "equal", (a, b) => a === b, "Long Integer", "Long Integer");
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  Test.assertion(undefined, "equal", Primitive_object.equal, undefined, undefined);
});

Test.test("QueryInfo record can be constructed", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, "qry_ActiveOrders", "qry_ActiveOrders");
  Test.assertion(undefined, "equal", (a, b) => a === b, "select", "select");
});

Test.test("RelationshipInfo record can be constructed", () => {
  let rel_columns = ["CustomerID"];
  let rel_foreignColumns = ["ID"];
  Test.assertion(undefined, "equal", (a, b) => a === b, "FK_Orders_Customers", "FK_Orders_Customers");
  Test.assertion(undefined, "equal", Primitive_object.equal, rel_columns, ["CustomerID"]);
  Test.assertion(undefined, "equal", Primitive_object.equal, rel_foreignColumns, ["ID"]);
});

Test.test("TableSchema record can be constructed", () => Test.assertion(undefined, "equal", (a, b) => a === b, "Products", "Products"));

Test.test("UnknownMetadata all-flags-true record", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
});

Test.test("QueryResult success record", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  Test.assertion(undefined, "equal", (a, b) => a === b, 0, 0);
  Test.assertion(undefined, "equal", Primitive_object.equal, undefined, undefined);
});

Test.test("QueryResult failure record with error", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, false, false);
  Test.assertion(undefined, "equal", Primitive_object.equal, "Syntax error in SQL", "Syntax error in SQL");
});

Test.test("MutationResult success record", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  Test.assertion(undefined, "equal", (a, b) => a === b, 5, 5);
});

Test.test("MutationResult failure record", () => {
  Test.assertion(undefined, "equal", (a, b) => a === b, false, false);
  Test.assertion(undefined, "equal", Primitive_object.equal, "Table not found", "Table not found");
});

/*  Not a pure module */
