// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";

function integrationConnectionString() {
  return "";
}

function isIntegrationConfigured() {
  let connStr = "";
  return connStr.length > 0;
}

Test.test("OdbcAdapter integration: connect to real ODBC data source", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: disconnect closes connection cleanly", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: isConnected reflects actual state", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: executeQuery returns real rows from ODBC", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: insertData writes to real ODBC table", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: updateData modifies existing rows", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: deleteData removes rows", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: executeRawSql runs arbitrary SQL", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: exportData produces output file", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: connect fails gracefully with invalid DSN", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

Test.test("OdbcAdapter integration: executeQuery fails gracefully when disconnected", () => {
  if (isIntegrationConfigured()) {
    return Test.assertion(undefined, "equal", (a, b) => a === b, false, true);
  } else {
    return Test.assertion(undefined, "equal", (a, b) => a === b, true, true);
  }
});

export {
  integrationConnectionString,
  isIntegrationConfigured,
}
/*  Not a pure module */
