// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";

let queryResponses = [
  [
    "SELECT * FROM Products",
    {
      rows: [
        {
          id: {
            TAG: "Int",
            _0: 1
          },
          name: {
            TAG: "Str",
            _0: "Widget"
          }
        },
        {
          id: {
            TAG: "Int",
            _0: 2
          },
          name: {
            TAG: "Str",
            _0: "Gadget"
          }
        }
      ],
      columns: [
        "id",
        "name"
      ],
      count: 2,
      statement: "SELECT * FROM Products"
    }
  ],
  [
    "SELECT * FROM Orders",
    {
      rows: [{
          id: {
            TAG: "Int",
            _0: 10
          },
          status: {
            TAG: "Str",
            _0: "shipped"
          }
        }],
      columns: [
        "id",
        "status"
      ],
      count: 1,
      statement: "SELECT * FROM Orders"
    }
  ]
];

let lastQuery = {
  contents: ""
};

let callCount = {
  contents: 0
};

function query(sql, _params) {
  lastQuery.contents = sql;
  callCount.contents = callCount.contents + 1 | 0;
  let response = queryResponses[0];
  return Promise.resolve({
    TAG: "Ok",
    _0: response[1]
  });
}

function tables(_catalog, _schema, _table, _tableType) {
  return Promise.resolve({
    TAG: "Ok",
    _0: []
  });
}

function columns(_catalog, _schema, _table, _column) {
  return Promise.resolve({
    TAG: "Ok",
    _0: []
  });
}

function close() {
  return Promise.resolve();
}

let FakeConnection = {
  queryResponses: queryResponses,
  lastQuery: lastQuery,
  callCount: callCount,
  query: query,
  tables: tables,
  columns: columns,
  close: close
};

Test.test("OdbcAdapter connect resolves to Ok(true)", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("OdbcAdapter disconnect resolves to Ok(unit)", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("OdbcAdapter isConnected returns Ok(true) when connected", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("OdbcAdapter isConnected returns Ok(false) when not connected", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("executeQuery returns Ok with rows and columns", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("executeQuery normalizes OdbcValue rows to JSON", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("executeQuery returns error when not connected", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("insert builds correct INSERT SQL from record dict", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("insert returns Ok with affected=1 on success", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("update with dict WHERE builds correct UPDATE SQL", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("update with raw WHERE builds correct SQL", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("update returns Ok with affected count", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("delete with dict WHERE builds correct DELETE SQL", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("delete with raw WHERE builds correct SQL", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("delete with None WHERE builds unconditional DELETE", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("delete returns Ok with affected count", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

Test.test("executeRawSql executes arbitrary SQL and returns affected count", () => Test.assertion(undefined, "equal", (a, b) => a === b, true, true));

export {
  FakeConnection,
}
/*  Not a pure module */
